{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=powercontent}
<input type="checkbox" name="{$attribute_base}_{$class_attribute.identifier}_ContentObjectAttribute_data_boolean_pcattributeid" value="" />
{/default}