{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=powercontent}
{let countries=fetch( 'content', 'country_list' )
     class_content=$class_attribute.content}

<select name="{$attribute_base}_{$class_attribute.identifier}_ContentObjectAttribute_country_pcattributeid[]" {if $class_content.multiple_choice}multiple="multiple"{/if}>
     {if $class_content.multiple_choice|not}
        <option  value="">{'Not specified'|i18n( 'design/standard/content/datatype' )}</option>
     {/if}
{foreach $countries as $key => $current_country}
      <option value="{$current_country.Alpha2}">{$current_country.Name}</option>
{/foreach}
</select>

{/let}
{/default}