{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base='powercontent'
         html_class='full'}
<textarea class="{eq( $html_class, 'half' )|choose( 'box', 'halfbox' )}" name="{$attribute_base}_{$class_attribute.identifier}_ContentObjectAttribute_data_text_pcattributeid" cols="70" rows="{$class_attribute.data_int1}"></textarea>
{/default}
