{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=powercontent}
<input type="hidden" name="MAX_FILE_SIZE" value="{$class_attribute.data_int1}000000"/>
<input class="box" name="{$attribute_base}_{$class_attribute.identifier}_ContentObjectAttribute_data_binaryfilename_pcattributeid" type="file" />
{/default}
