{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=powercontent}
<input class="box" type="text" size="10" name="{$attribute_base}_{$class_attribute.identifier}_ContentObjectAttribute_data_text_pcattributeid" value="" />
{/default}