{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base='powercontent'}

<select name="{$attribute_base}_{$class_attribute.identifier}_ContentObjectAttribute_ezenhancedselect_selected_array_pcattributeid[]" {section show=$class_attribute.content.is_multiselect}multiple="multiple"{/section}>
    {section var=Options loop=$class_attribute.content.options}
    <option value="{$Options.item.identifier}">{$Options.item.name|wash(xhtml)}</option>
    {/section}
</select>

{/default}