{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=powercontent}
<input type="text" name="{$attribute_base}_{$class_attribute.identifier}_ContentObjectAttribute_data_integer_pcattributeid" size="10" />
{/default}