{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=powercontent}

{* Always set the .._selected_array_.. variable, this circumvents the problem when nothing is selected. *}
<input type="hidden" name="{$attribute_base}_{$class_attribute.identifier}_ContentObjectAttribute_ezselect_selected_array_pcattributeid" value="">

<select name="{$attribute_base}_{$class_attribute.identifier}_ContentObjectAttribute_ezselect_selected_array_pcattributeid[]" {section show=$class_attribute.content.is_multiselect}multiple{/section}>
{section var=Options loop=$class_attribute.content.options}
<option value="{$Options.item.id}">{$Options.item.name|wash( xhtml )}</option>
{/section}
</select>

{/default}
