{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base='powercontent'
         html_class='full'}
<input class="{eq( $html_class, 'half' )|choose( 'box', 'halfbox' )}" type="text" size="70" name="{$attribute_base}_{$class_attribute.identifier}_ContentObjectAttribute_ezstring_data_text_pcattributeid" value="" />
{/default}