{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base='powercontent'}

{* URL. *}
<div class="block">
    <label>{'URL'|i18n( 'design/standard/content/datatype' )}:</label>
    <input class="box" type="text" size="70" name="{$attribute_base}_{$class_attribute.identifier}_ContentObjectAttribute_ezurl_url_pcattributeid" />
</div>

{* Text. *}
<div class="block">
    <label>{'Text'|i18n( 'design/standard/content/datatype' )}:</label>
    <input class="box" type="text" size="70" name="{$attribute_base}_{$class_attribute.identifier}_ContentObjectAttribute_ezurl_text_pcattributeid" />
</div>

{/default}
